pipeline {
    agent any
    environment {
        GCP_REGION = 'asia-southeast1'
        GCP_PROJECT_ID = 'jenkins-services'
        ARTIFACT_REPO = 'my-electron-repo'
        IMAGE_NAME = 'electron-noise'
        IMAGE_TAG = 'latest'
        GOOGLE_APPLICATION_CREDENTIALS = credentials('gcp-artifact-key')
    }
    stages {
        stage('Build & Push Docker Image') {
            steps {
                withCredentials([file(credentialsId: 'gcp-artifact-key', variable: 'GCP_KEYFILE')]) {
                    sh """
                      gcloud auth activate-service-account --key-file="${GCP_KEYFILE}"
                      gcloud config set project ${GCP_PROJECT_ID}
                      gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev --quiet

                      docker build -t ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REPO}/${IMAGE_NAME}:${IMAGE_TAG} .
                      docker push ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }
    }
}
